### ISSUE TITLE
CSP issue

### ISSUE THREAD

**Issue by ganeddact** [swissup/module-speculation-rules#1]
Hi, using this module I'm getting a "Refused to execute inline script because it violates the following Content Security Policy directive [...]" in the browser console.
I can see that the whole script is wrapped using the $secureRenderer->renderTag method on line 25 in view/frontend/templates/scripts.phtml and that's ok
But I get the error on line 19 where "_document.body.append(speculationScript);".
Shouldn't any created script element have a nonce attribute attached to it to avoid any issue?

Thanks

**Comment by 0m3r** [comment]
What is your Magento version?
In my case, it's 2.4.7 and ->renderTag  -> [Magento/Csp/Helper/InlineUtil.php](https://github.com/magento/magento2/blob/11e7d89380c3ef9b9bd18c1d8b7815b0fad96e34/app/code/Magento/Csp/Helper/InlineUtil.php#L216) added 'nonce' attribute by itself.

```php
public function processTag(TagData $tagData): TagData
    {
        //Processing tag data
       ...

            //Adding required policies.
            ...

            if ($tagData->getContent()
                && !empty(self::$tagMeta[$tagData->getTag()]['hash'])
                && $this->isInlineDisabled(self::$tagMeta[$tagData->getTag()]['id'])
            ) {
                /** create new tagData with a nonce */
                if ($tagData->getTag() === 'script') {
                    $nonce = $this->nonceProvider->generateNonce();
                    $tagAttributes = $tagData->getAttributes();
                    $tagAttributes['nonce'] = $nonce;
                    $newTagData = new TagData(
                        $tagData->getTag(),
                        $tagAttributes,
                        $tagData->getContent(),
                        $tagData->isTextContent()
                    );

                    $tagData = $newTagData;
```

![image](https://github.com/user-attachments/assets/dcf57960-2abb-4c2b-8de7-8e3b9e2c7135)
but it's only if isInlineDisabled("script-src") returns true
```xml
<csp>
           <policies>
               <storefront>
                   <scripts>
                       <inline>0</inline>
                   </scripts>
               </storefront>
           </policies>
       </csp>
```

**Comment by ganeddact** [comment]
My Magento version is 2.4.6-p6.
I get the nonce attribute added to that script and it's correct. But if that script creates a new script tag and appends it to the DOM, the new script tag needs a nonce itself or it will get flagged for CSP violation.
Hope this is more clear.

**Comment by 0m3r** [comment]
Thank you. I will research it 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#allowing_speculation_rules

**Comment by ganeddact** [comment]
I've made a quick test, changed  vendor/swissup/module-speculation-rules/view/frontend/templates/scripts.phtml                                                               
as following:
1) added 
$cspNonceProvider = \Magento\Framework\App\ObjectManager::getInstance()->get('\Magento\Csp\Helper\CspNonceProvider');
$nonce = $cspNonceProvider->generateNonce();
on line 10;

2) Added 
speculationScript.setAttribute("nonce", "$nonce");
on line 17

On checkout, the error I was seeing in my original post is gone.
Use of objectManager is not good practice but it was the fastest way to figure out.
You'll probably need to add the CspNonceProvider to the script.phtml block class and add the nonce attribute to the dynamically generated script tag.
Hope this helps
