### ISSUE TITLE
Old Magento versions compatibility

### ISSUE THREAD

**Issue by roma84** [swissup/module-speculation-rules#2]
```bash
[a27d7785@cloudhost-6167188 html]$ bin/magento setup:di:compile
Compilation was started.
Area configuration aggregation... 5/9 [===============>------------] 55% 31 secs 476.0 MiB
In ClassReader.php line 57:
Impossible to process constructor argument Parameter #1 [ ?Magento\Csp\Helper\CspNonceProvider $cspNonceProvider = NULL ] of Swissup\Specul
ationRules\ViewModel\Config class
In GetParameterClassTrait.php line 34:
Class "Magento\Csp\Helper\CspNonceProvider" does not exist
```

**Comment by ganeddact** [comment]
Hi, sorry to reopen but the fix now breaks both old and new versions.
The objectManager is not initialised so we end up with a create method used on a null object.
You should add this line around lines 28/29
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

Thanks

**Comment by 0m3r** [comment]
Hi @ganeddact 

Thank you for your attention and I'm sorry for any inconvenience caused by the recent update. We appreciate your patience and feedback.

**Comment by ganeddact** [comment]
No worries, a small error can happen. Thanks for your work
